#!/bin/bash

# Displays status of important services
# Отображает статус важных сервисов

# Colors
# Цвета
W="\e[0;39m"
G="\e[1;32m"
R="\e[1;31m"
Y="\e[1;33m"

# Service list add service 
# Список сервисов добавить сервисы нужные
services=(
    "kubelet.service"
    "zabbix-agent2.service" 
    "containerd-deckhouse.service"
)

# Sort services
# Сортировка сервисов
IFS=$'\n' sorted_services=($(sort <<<"${services[*]}"))
unset IFS

echo -e "${W}services:"

for service in "${sorted_services[@]}"; do
    # Check if service exists
    # Проверка существования сервиса
    if ! systemctl list-unit-files | grep -q "^${service}"; then
        echo -e "  ${service}: ${Y}not installed${W}"
        continue
    fi
    
    status=$(systemctl is-active "$service" 2>/dev/null)
    if [[ "$status" == "active" ]]; then
        echo -e "  ${service}: ${G}${status}${W}"
    else
        echo -e "  ${service}: ${R}${status}${W}"
    fi
done
